import Head from "next/head";
import Heading from "../../components/heading";
import { BASE_URL } from "../../constant/api";
export default function HotelDetails() {
  return (
    <div>
      <Head>
        <title>Holidaze | Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        ></meta>
      </Head>

      <main>
        <Heading headingText="Details page" />
      </main>
    </div>
  );
}
