import Head from "next/head";
import Image from "next/image";
import JumbotronLarge from "../components/jumbotron/jumbotron";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Holidaze</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <JumbotronLarge />
        <h1>Homepage</h1>
        <h2>This is a sub-header</h2>
        <h3>Sub-header number 3</h3>
        <p>Lorem ipsum shdfhskjdhfkjshdfkjsahdkjfhksjdahkhsdfjdsk</p>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
