import Head from "next/head";
import Heading from "../components/heading";
import AmusementsCards from "../components/cards/amusements";
import JumbotronLarge from "../components/jumbotron/jumbotronLarge";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Holidaze</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <JumbotronLarge />

        <AmusementsCards />
      </main>
    </div>
  );
}
