import Head from "next/head";
import Heading from "../components/heading";
import JumbotronSmall from "../components/jumbotron/jumbotronSmall";
import Header3 from "../assets/images/headers/header3.jpg";
// import ContactForm from "../components/contact/contactForm";

export default function Booking() {
  return (
    <div>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <JumbotronSmall imgPath={Header3} />
        <Heading headingText="Contact" />
        {/* <ContactForm /> */}
      </main>
    </div>
  );
}
