import Head from "next/head";
// import Heading from "../components/heading";
import AmusementsCards from "../components/cards/amusements";
import JumbotronLarge from "../components/jumbotron/jumbotronLarge";
import { BASE_URL } from "../constant/api";
import Searchbar from "../components/search/search";

export default function Home({ hotels }) {
  const hotelNames = hotels.map((hotel) => hotel.name);
  return (
    <div>
      <Head>
        <title>Holidaze | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        ></meta>
      </Head>

      <main>
        <JumbotronLarge />
        <Searchbar hotelNames={hotelNames} />
        <AmusementsCards />
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  let hotels = [];

  try {
    const response = await axios.get(BASE_URL + "accomodations/?populate=*");
    hotels = response.data;
  } catch (error) {
    console.log(error);
  }

  return {
    props: {
      hotels: hotels,
    },
  };
}
